export const CARGAR_JUGADORES = "CARGAR_JUGADORES";
export const NEW_HEANDLIN = "NEW_HEANDLIN ";
export const NEW_ALTERNATE = "NEW_ALTERNATE ";
export const DELETE_ALTERNATE = "DELETE_ALTERNATE ";
export const DELETE_HEANDLINE = "DELETE_HEANDLINE ";
